"""migration1

Revision ID: 5fe703e4071b
Revises: b066726f07cf
Create Date: 2021-06-22 14:55:54.715160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe703e4071b'
down_revision = 'b066726f07cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
